name: CI to Staging
on:
  push:
    branches: [main]
jobs:
  common-ci:
    uses: vatusa/gitops/.github/workflows/common-ci.yml@main
    with:
      image-name: 'portal'
      relative-path: 'apps/vatusa/'
    secrets: inherit

