name: CI to Staging
on:
  push:
    branches: [master]
jobs:
  common-ci:
    uses: portal/gitops/.github/workflows/common-ci.yml@main
    with:
      image-name: "portal"
      kustomization-folder: "webapps"
      relative-path: "apps/vatusa/"
    secrets: inherit
