name: Production Release
on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit SHA to checkout (optional)'
        required: false
        default: ''
jobs:
  common-release-portal:
    uses: vatusa/gitops/.github/workflows/common-release.yml@main
    with:
      image-name: 'portal'
      kustomization-folder: 'webapps'
    secrets: inherit
  common-release-staff:
    uses: vatusa/gitops/.github/workflows/common-release.yml@main
    with:
      image-name: 'staff'
      kustomization-folder: 'webapps'
    secrets: inherit